
[theme]
primaryColor = "#FFD700"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#002147"
font = "sans serif"

[server]
port = 8501
enableCORS = false
headless = true

[browser]
gatherUsageStats = false

[client]
showErrorDetails = false
