[theme]
primaryColor = "#003366"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#333333"
font = "sans serif"

[client]
showErrorDetails = false
toolbarMode = "auto"

[logger]
level = "info"

[browser]
gatherUsageStats = false

[server]
maxUploadSize = 500
enableXsrfProtection = true
